import type { NextPage } from "next";
import Head from "next/head";

const Coaching: NextPage = () => {
  return (
    <div>
      <Head>
        <title>KRAUSS Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>Test</p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Coaching;
