import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className="w-screen"
          style={{
            height: "93vh",
            backgroundColor: "#F5F6FA",
            overflow: "hidden",
          }}
        >
          <div className="flex flex-col items-center justify-center flex-grow mx-auto space-y-5 text-center text-gray-700 xl:flex-row xl:space-x-32 md:space-y-0 xl:py-0 md:pb-28 xl:p-40 xl:text-left">
            <div className="w-full text-gray-700 transition duration-500 ease-in-out transform">
              <div className="flex flex-col flex-wrap p-5 mx-auto md:items-center md:flex-row">
                <a href="/" className="focus:outline-none" />
                <div className="inline-flex items-center mx-auto md:mx-0">
                  <img
                    className="w-40"
                    src="https://www.krauss-friends.com/app/download/8035797161/Krauss-Logo-Boden.png?t=1625756538"
                  />
                </div>
                <nav className="flex flex-wrap items-center justify-center text-base md:ml-auto md:mr-auto"></nav>
                <a
                  className="w-auto px-8 py-2 my-2 text-base font-medium text-gray-800"
                  href="tel:+4981919375923"
                >
                  Rufen Sie jetzt unseren Vertrieb an:
                  <br className="md:hidden" />
                  <span className="text-gray-800 underline">
                    +49 8191 93759-23
                  </span>
                </a>
              </div>
            </div>
          </div>
          <section className="flex flex-col items-center justify-center flex-grow mx-auto text-center text-gray-700 xl:flex-row xl:space-x-32 xl:px-40 md:h-screen xl:text-left">
            <div className="flex flex-col flex-initial w-2/3 xl:py-40">
              <h1
                className="mb-8 text-xl font-semibold leading-tight text-gray-800 md:text-2xl dark:text-white xl:text-4xl xl:leading-tight"
                style={{
                  fontFamily: '"Frank Ruhl Libre", serif',
                  textTransform: "none",
                }}
              >
                Verkaufserfolg ist trainierbar.
                <br />
                <span
                  style={{
                    fontFamily: '"Frank Ruhl Libre", serif',
                    background:
                      "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
                  }}
                >
                  Endlich mehr Neukunden.
                </span>
              </h1>
              <p className="mb-8 text-base font-medium text-gray-500 md:text-2xl">
                Ich unterstütze Ihren Vertrieb, Potenziale zu erkennen und
                Chancen im Verkaufsgespräch zu ergreifen, um mit gewonnener
                Motivation mehr Neukunden zu gewinnen.
              </p>
              <div className="flex flex-col items-center mb-8 space-x-3 space-y-3 md:flex-row md:space-y-0">
                <div className="flex -space-x-2 overflow-hidden">
                  <img
                    className="inline-block w-8 h-8 rounded-full ring-2 ring-white"
                    src="https://i.ibb.co/1zj9jvz/Gert-Behre.png"
                    alt=""
                  />{" "}
                  <img
                    className="inline-block w-8 h-8 rounded-full ring-2 ring-white"
                    src="https://i.ibb.co/bd3kKfB/Stephan-Kotterer.png"
                    alt=""
                  />{" "}
                  <img
                    className="inline-block w-8 h-8 rounded-full ring-2 ring-white"
                    src="https://i.ibb.co/Js04MG9/Jan-Hauschildt.png"
                    alt=""
                  />{" "}
                  <img
                    className="inline-block w-8 h-8 rounded-full ring-2 ring-white"
                    src="https://i.ibb.co/yVPhbgQ/Michael-Schwab.png"
                    alt=""
                  />
                </div>
                <p className="text-xs">
                  <b>Herr Michael Schwab, Leiter CRM Innendienst</b> und{" "}
                  <b>über 913 erfolgreiche Verkäufer</b> trainieren regelmäßig
                  für mehr Erfolg im Verkauf.
                </p>
              </div>
              <a
                target="_blank"
                href="https://calendly.com/krauss-friends/kennenlerngespraech"
                style={{ color: "white !important" }}
                className="items-center self-start px-12 py-4 mr-2 text-lg font-medium text-white uppercase transition duration-500 ease-in-out transform border-0 rounded-lg shadow-lg xl:flex hiddenNon primary-cta hover:shadow-inner hover:-translate-y-1 hover:scale-110 focus:outline-none"
              >
                Erstgespräch reservieren
                <svg
                  className="w-5 h-5 ml-2 fill-current color-white"
                  clasversion="1.1"
                  id="Layer_1"
                  x="0px"
                  y="0px"
                  viewBox="-49 141 512 512"
                >
                  <path
                    id="XMLID_11_"
                    d="M-24,422h401.645l-72.822,72.822c-9.763,9.763-9.763,25.592,0,35.355c9.763,9.764,25.593,9.762,35.355,0 l115.5-115.5C460.366,409.989,463,403.63,463,397s-2.634-12.989-7.322-17.678l-115.5-115.5c-9.763-9.762-25.593-9.763-35.355,0 c-9.763,9.763-9.763,25.592,0,35.355l72.822,72.822H-24c-13.808,0-25,11.193-25,25S-37.808,422-24,422z"
                  ></path>
                </svg>
              </a>
              <p className="self-start pt-3 text-sm text-gray-500 cursor-pointer hiddenNon md:block">
                In nur 60 Sekunden online einen freien Termin suchen
              </p>
            </div>
            <div
              target="_blank"
              className="flex flex-col items-center justify-center w-5/6 xl:w-1/2 md:self-end"
            >
              <a
                target="_blank"
                href="https://calendly.com/krauss-friends/kennenlerngespraech"
                style={{ color: "white !important" }}
                className="flex items-center px-12 py-4 text-xs font-medium text-white text-teal-500 uppercase transition duration-500 ease-in-out transform border-0 rounded-lg shadow-lg xl:hidden primary-cta hover:shadow-inner hover:-translate-y-1 hover:scale-110 focus:outline-none"
              >
                Erstgespräch reservieren
              </a>
              <p className="pt-3 text-sm text-gray-500 cursor-pointer xl:hidden">
                In nur 60 Sekunden online einen freien Termin suchen
              </p>
              <img
                src="https://i.ibb.co/mDbxPWv/johannes-krauss-1-1.png"
                alt="Johannes Krauss"
                className="w-full pt-10 md:hidden md:pt-0"
              />{" "}
              <img
                src="https://i.ibb.co/SB421rq/Johannes-Krauss.png"
                alt="Johannes Krauss"
                className="w-full pt-10 hiddenNon md:block md:pt-0"
              />
            </div>
          </section>
        </div>

        <section className="z-50 text-gray-600 transform -translate-y-16 body-font">
          <div className="container px-5 pt-10 mx-auto md:pt-0 2xl:w-3/5">
            <div className="flex flex-wrap">
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 fa fa-trophy fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Motivieren durch mehr Erfolg in der Neukundengewinnung
                    </h2>
                  </div>
                </div>
              </div>
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 fas fa-funnel-dollar fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Mit der Einwandbehandlung den Abschluss vorbereiten
                    </h2>
                  </div>
                </div>
              </div>
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 far fa-smile-beam fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Kunden begeistern durch Storytelling
                    </h2>
                  </div>
                </div>
              </div>
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 fas fa-hands-helping fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Erfolgreiches Verkaufsgespräch führen
                    </h2>
                  </div>
                </div>
              </div>
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 fas fa-comment-dots fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Im Kopf des Kunden argumentieren
                    </h2>
                  </div>
                </div>
              </div>
              <div className="w-full p-2 cursor-pointer md:w-1/3">
                <div className="flex items-center h-full p-4 bg-white rounded-lg shadow-xl">
                  <div className="flex-shrink-0 w-12 h-12 mr-4 fas fa-seedling fa-3x r"></div>
                  <div className="flex-grow">
                    <h2
                      className="font-medium text-gray-900 title-font"
                      style={{ textTransform: "none" }}
                    >
                      Bedarf wecken - seinen eigenen Markt machen
                    </h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <div className="py-5">
          <h1
            className="px-5 mb-8 text-xl font-semibold leading-tight text-gray-800 md:text-center dark:text-white xl:text-4xl xl:leading-tight"
            style={{
              fontFamily: '"Frank Ruhl Libre", serif',
              textTransform: "none",
            }}
          >
            <span
              style={{
                background:
                  "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
              }}
            >
              Erkennen Sie
            </span>{" "}
            Ihren Vertrieb hier wieder?
          </h1>
          <section className="text-gray-400 body-font">
            <div className="container mx-auto md:px-5 2xl:w-3/5">
              <div className="flex flex-wrap">
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font text-md"
                        style={{ textTransform: "none" }}
                      >
                        <strong>Zu wenig Abschlüsse</strong> aus der
                        Angebotsnachbearbeitung
                      </p>
                    </div>
                  </div>
                </div>
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font text-md"
                        style={{ textTransform: "none" }}
                      >
                        Die Kunden sagen "
                        <strong>Wir haben keinen Bedarf</strong>" oder "Kein
                        Interesse"
                      </p>
                    </div>
                  </div>
                </div>
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Entscheider können nicht mehr besucht werden, weil Sie
                        im Home-Office sind oder{" "}
                        <strong>nur selten vor Ort</strong>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Es bleibt{" "}
                        <strong>keine Zeit für Neukundengewinnung</strong>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font"
                        style={{ textTransform: "none" }}
                      >
                        <strong>Termine vor Ort</strong> nicht mehr möglich
                        (Abstandsregeln, Kettengeschäft...)
                      </p>
                    </div>
                  </div>
                </div>
                <div className="w-full p-2 cursor-pointer md:w-1/3">
                  <div className="flex items-center h-full p-4">
                    <div className="flex-shrink-0 w-4 h-4 mr-4 fas fa-long-arrow-alt-right"></div>
                    <div className="flex-grow">
                      <p
                        className="font-medium text-gray-400 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Kunde behauptet "Das Produkt ist{" "}
                        <strong>zu teuer</strong>"
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>

        <section id="your-profit" className="container px-5 mx-auto 2xl:w-3/5">
          <div className="py-3">
            <div className="flex flex-col items-start mx-auto my-12 sm:container md:flex-row">
              <div className="sticky flex flex-col w-full mt-2 md:top-36 lg:w-1/2 md:px-8">
                <p className="font-semibold text-gray-400 uppercase tracking-loose">
                  So kann ich Ihnen helfen
                </p>
                <h1
                  className="mb-12 text-4xl font-semibold leading-tight text-gray-800 dark:text-white xl:leading-tight"
                  style={{
                    fontFamily: '"Frank Ruhl Libre", serif',
                    textTransform: "none",
                  }}
                >
                  <span
                    style={{
                      background:
                        "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
                    }}
                  >
                    Verdoppeln Sie Ihre Verkaufsleistung
                  </span>{" "}
                  mit unserem Vertriebstraining.
                </h1>
                <a
                  onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
                  target="_blank"
                  href="https://calendly.com/krauss-friends/kennenlerngespraech"
                  style={{ color: "white !important" }}
                  className="flex items-center self-start px-12 py-4 mr-2 font-medium text-white uppercase transition duration-500 ease-in-out transform border-0 rounded-lg shadow-lg primary-cta hover:shadow-inner hover:-translate-y-1 hover:scale-110 focus:outline-none text-md"
                >
                  Erstgespräch reservieren
                  <svg
                    className="w-5 h-5 ml-2 fill-current color-white"
                    clasversion="1.1"
                    id="Layer_1"
                    x="0px"
                    y="0px"
                    viewBox="-49 141 512 512"
                  >
                    <path
                      id="XMLID_11_"
                      d="M-24,422h401.645l-72.822,72.822c-9.763,9.763-9.763,25.592,0,35.355c9.763,9.764,25.593,9.762,35.355,0 l115.5-115.5C460.366,409.989,463,403.63,463,397s-2.634-12.989-7.322-17.678l-115.5-115.5c-9.763-9.762-25.593-9.763-35.355,0 c-9.763,9.763-9.763,25.592,0,35.355l72.822,72.822H-24c-13.808,0-25,11.193-25,25S-37.808,422-24,422z"
                    ></path>
                  </svg>
                </a>
                <p
                  onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
                  className="self-start pt-3 text-sm text-gray-400 cursor-pointer"
                >
                  In nur 60 Sekunden online einen freien Termin suchen
                </p>
              </div>
              <div className="sticky pt-10 ml-0 md:ml-12 lg:w-1/2 md:pt-0">
                <div className="w-full h-full mx-auto sm:container">
                  <p className="text-lg font-medium text-gray-400">
                    {/*<u>Wenn Ihre Antwort auf die vorige Frage <strong>“ja”</strong> lautet</u>, kann ich Ihnen helfen.<br />
                        <br />*/}
                    Für namhafte Marken{" "}
                    <span className="underline">
                      betreiben wir seit vielen Jahren in unserem Vertriebsteam
                      die tägliche Terminvereinbarung in der Neukundenakquise
                    </span>
                    . Und deshalb glauben wir zu wissen was die
                    Herausforderungen jetzt und zukünftig sein werden -{" "}
                    <strong>Wir leben Vertrieb.</strong>
                    <br />
                    <br />
                    {/*Wir verstehen, dass Ihr Vertrieb damit beschäftigt ist Kunden zu betreuen. Um so wichtiger ist es deshalb Ihren Vertrieb ständig bei Ihrer Neukundengewinnung zu unterstützen, um Ihr
                        Geschäft wachsen zu lassen.<br />
                        <br/>*/}
                    Wir <strong>motivieren &amp; trainieren</strong> Ihr Team in
                    echten Praxis Situationen auch außerhalb des Seminarraums
                    und machen Erfolg erlebbar. Die gewonnen Erkenntnisse aus
                    der Übung machen Lust auf Verhaltensänderungen.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="container px-5 mx-auto text-gray-400 2xl:w-3/5">
          <div className="container flex flex-col px-5 py-16 mx-auto lg:items-center md:flex-row">
            <div className="w-full mb-10 lg:w-5/6 lg:max-w-lg md:w-1/2">
              <img
                className="object-cover object-center rounded"
                alt="Artur Polak - Gebietsverkaufsleiter"
                loading="lazy"
                src="https://www.krauss-friends.com/app/download/8105062461/8693ac.png?t=1625738080"
              />
            </div>
            <div className="flex flex-col items-start text-left lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16">
              <p className="mb-12 text-base font-medium leading-relaxed text-gray-400">
                "Das Vertriebstraining war{" "}
                <i>
                  sehr kurzweilig, abwechslungsreich und vor allem praxisbezogen
                </i>
                . Den größten Aha-Effekt löste bei mir die Übung aus, andere
                Verkäufer aus der Kundenrolle zu erleben und zu analysieren.
                Seitdem nehme ich auch in meinem Arbeitsalltag gedanklich immer
                wieder die Perspektive des Kunden ein,{" "}
                <strong>
                  behalte so die Gesprächsführung und bin erfolgreicher
                </strong>
                ."
              </p>
              <h2 className="mb-8 text-xs font-semibold tracking-widest text-black text-gray-400 uppercase title-font">
                Artur Polak
                <br />
                Gebietsverkaufsleiter Gebiet Süd/Ost
              </h2>
            </div>
          </div>
        </section>

        <section className="container mx-auto text-gray-600 body-font md:px-5 2xl:w-3/5">
          <div className="container flex flex-col px-5 mx-auto md:py-20 md:flex-wrap">
            <div className="flex flex-wrap w-full mb-20">
              <h1
                className="mb-4 text-4xl font-semibold leading-tight text-gray-800 dark:text-white xl:leading-tight lg:w-1/3 lg:mb-0"
                style={{
                  fontFamily: '"Frank Ruhl Libre", serif',
                  textTransform: "none",
                }}
              >
                Eindrücke aus unserem{" "}
                <span
                  style={{
                    fontFamily: '"Frank Ruhl Libre", serif',
                    background:
                      "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
                  }}
                >
                  Vertriebstraining
                </span>
              </h1>
              <p className="mx-auto text-base font-medium leading-relaxed text-gray-400 lg:pl-6 lg:w-2/3">
                Unsere Trainingsmethoden gewährleisten Wissensaufbau durch
                systemische Arbeitssequenzen. Der Wissenstransfer reduziert sich
                auf das Wesentliche und ist sofort für die Praxis nutzbar. Ihr
                Vertrieb hat die Möglichkeit sofort seine Leistung zu
                verdoppeln. Wir trainieren nach Ihren Anforderungen sowohl
                online als auch offline. Wirksam und Praxisnah.
              </p>
            </div>
            <div className="flex flex-wrap -m-1 md:-m-2">
              <div className="flex flex-wrap w-1/2">
                <div className="w-1/2 p-1 md:p-2">
                  <img
                    alt="Training Gruppenarbeit"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://image.jimcdn.com/app/cms/image/transf/dimension=660x10000:format=png/path/s136c472730450c10/image/ib3ff735be07090b9/version/1621596236/training-gruppenarbeit.png"
                  />
                </div>
                <div className="w-1/2 p-1 md:p-2">
                  <img
                    alt="Golf Analogieübung beim Vertriebstraining"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://www.krauss-friends.com/app/download/8105144261/_DSC4647-min.png?t=1625756283"
                  />
                </div>
                <div className="w-full p-1 md:p-2">
                  <img
                    alt="Flipchart bearbeiten im Team"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://www.krauss-friends.com/app/download/8105144061/_DSC4662-min.png?t=1625756102"
                  />
                </div>
              </div>
              <div className="flex flex-wrap w-1/2 mx-auto">
                <div className="w-full p-1 md:p-2">
                  <img
                    alt="gallery"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://www.krauss-friends.com/app/download/8105114861/Mitarbeiter+Interview+Krauss+GmbH+2-19+screenshot.png?t=1625750993"
                  />
                </div>
                <div className="w-1/2 p-1 md:p-2">
                  <img
                    alt="gallery"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://www.krauss-friends.com/app/download/8111814061/20210729_112121.jpeg?t=1629117333"
                  />
                </div>
                <div className="w-1/2 p-1 md:p-2">
                  <img
                    alt="gallery"
                    className="block object-cover object-center w-full h-full rounded"
                    src="https://www.krauss-friends.com/app/download/8105144761/_DSC4611-min.png?t=1625756542"
                  />
                </div>
              </div>
              <div className="flex flex-wrap w-full mx-auto">
                <div className="w-1/2 p-1 md:p-2">
                  <p className="text-left text-gray-400">
                    Präsenz Vertriebstraining mit erlebnisreicher Golf
                    Analogieübung, um das eigene Verhalten zu reflektieren, für
                    mehr Erfolg im nächsten Verkaufsgespräch.
                  </p>
                </div>
                <div className="w-1/2 p-1 md:p-2">
                  <p className="text-right text-gray-400">
                    Online Vertriebstraining mit interaktiven Whiteboard für
                    motivierte Übung um das nächste Verkaufsgespräch direkt zu
                    gewinnen und mehr Umsatz zu erzielen.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="container px-5 mx-auto 2xl:w-3/5">
          <div className="py-3">
            <div className="flex flex-col items-start mx-auto my-12 sm:container md:flex-row md:my-24">
              <div className="sticky flex flex-col w-full mt-2 md:top-36 lg:w-1/2 md:mt-12 md:px-8">
                <p className="font-semibold text-gray-400 uppercase tracking-loose">
                  Was Sie erwartet
                </p>
                <h1
                  className="mb-16 text-4xl font-semibold leading-tight text-gray-800 dark:text-white xl:leading-tight"
                  style={{
                    fontFamily: '"Frank Ruhl Libre", serif',
                    textTransform: "none",
                  }}
                >
                  So unterstützt das Vertriebstraining Ihren Verkäufern{" "}
                  <span
                    style={{
                      fontFamily: '"Frank Ruhl Libre", serif',
                      background:
                        "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
                    }}
                  >
                    die Ziele zu erreichen.
                  </span>
                </h1>
                <a
                  onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
                  target="_blank"
                  href="https://calendly.com/krauss-friends/kennenlerngespraech"
                  style={{ color: "white !important" }}
                  className="flex items-center self-start px-12 py-4 mr-2 font-medium text-white uppercase transition duration-500 ease-in-out transform border-0 rounded-lg shadow-lg primary-cta hover:shadow-inner hover:-translate-y-1 hover:scale-110 focus:outline-none text-md"
                >
                  Erstgespräch reservieren
                  <svg
                    className="w-5 h-5 ml-2 fill-current color-white"
                    clasversion="1.1"
                    id="Layer_1"
                    x="0px"
                    y="0px"
                    viewBox="-49 141 512 512"
                  >
                    <path
                      id="XMLID_11_"
                      d="M-24,422h401.645l-72.822,72.822c-9.763,9.763-9.763,25.592,0,35.355c9.763,9.764,25.593,9.762,35.355,0 l115.5-115.5C460.366,409.989,463,403.63,463,397s-2.634-12.989-7.322-17.678l-115.5-115.5c-9.763-9.762-25.593-9.763-35.355,0 c-9.763,9.763-9.763,25.592,0,35.355l72.822,72.822H-24c-13.808,0-25,11.193-25,25S-37.808,422-24,422z"
                    ></path>
                  </svg>
                </a>
                <p
                  onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
                  className="self-start pt-3 text-sm text-gray-400 cursor-pointer"
                >
                  In nur 60 Sekunden online einen freien Termin suchen
                </p>
              </div>
              <div className="flex"></div>
              <div className="sticky pt-10 ml-0 md:ml-12 lg:w-1/2 md:pt-0">
                <div
                  id="ahhh"
                  className="w-full h-full mx-auto space-y-6 sm:container sss"
                >
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/42-business-professional-services/interview.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Erstgespräch &amp; Kennenlernen
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Nicht nur die Menschen, Trainer &amp; Mitarbeiter, sondern
                      auch die Inhalte müssen mit <b>Ihren Herausforderungen</b>{" "}
                      zusammen passen.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/42-business-professional-services/interview.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Briefing &amp; Klare Zielsetzung
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Zusammen identifizieren wir und legen klare Ziele für Ihr
                      Verkaufstraining fest und fokussieren uns auf die
                      Entwicklung Ihrer Stärken.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/12-peoples-avatars/positive-thoughts.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Verhaltensänderung Ihrer Mitarbeiter
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Analogie Übungen in einem positiven Lernumfeld sichern ein
                      intensives Trainieren an der eigenen Performance. Die
                      Verhaltensänderung ist durch erfolgreiches Erleben
                      umgesetzt.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/44-hand-gestures/freedom.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Langfristige Verbesserung
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Effektive Follow-up Aktivitäten unterstützen eine
                      nachhaltig wirksame Trainingsinvestition.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/42-business-professional-services/meeting.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Sofortige Anwendung
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Unsere Trainingsmethoden gewährleisten Wissensaufbau durch
                      systemische Arbeitssequenzen. Der Wissenstransfer
                      reduziert sich auf das Wesentliche und ist sofort für die
                      Praxis nutzbar.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/12-peoples-avatars/motivation.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Mehr Motivation und Freude
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Motivation und Engagement der Mitarbeiter wachsen, somit
                      wird die Realisierung ambitionierter, und
                      Unternehmensziele wahrscheinlicher.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/42-business-professional-services/analysis.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Maximale Vertriebsperformance
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Im Vertrieb sind Trainings notwendig, um ihre Mitarbeiter
                      zu unterstützen und deren Performance zu verbessern, das
                      verschafft Ihrem Unternehmen Wettbewerbsvorteile.
                    </p>
                  </div>
                  <div className="relative flex items-center p-4 bg-white rounded-lg shadow-xl">
                    <img
                      alt="team"
                      className="flex-shrink-0 w-12 h-12 mr-4"
                      src="https://uxwing.com/wp-content/themes/uxwing/download/42-business-professional-services/analysis.svg"
                    />
                    <div className="flex-grow">
                      <h2
                        className="font-medium text-gray-900 title-font"
                        style={{ textTransform: "none" }}
                      >
                        Intervalltrainings für zeitnahe Erfolge bei sich und
                        Ihren Mitarbeitern
                      </h2>
                    </div>
                  </div>
                  <div className="relative pl-28">
                    <p className="font-semibold text-gray-500 text-md">
                      Intervall heißt für Ihren Vertrieb: kontinuierliches
                      Lernen und Umsetzen in Themeneinheiten, sind der Schlüssel
                      zum Erfolg.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="w-screen h-70" style={{ backgroundColor: "#F5F6FA" }}>
          <section className="flex flex-col-reverse items-center justify-center flex-grow h-full mx-auto text-center text-gray-700 xl:flex-row xl:space-x-32 md:space-y-10 md:space-y-0 xl:py-0 py-28 xl:p-40 md:w-5/6 xl:text-left">
            <div
              target="_blank"
              className="flex flex-col items-center justify-center w-5/6 xl:w-1/2 xl:h-5/6"
            >
              <img
                src="https://www.krauss-friends.com/app/download/8104229161/johannes-krauss-1+%281%29.png?t=1625479308"
                alt="Johannes Krauss - Vertriebstrainer"
                className="w-full md:pt-32"
              />
            </div>
            <div className="flex flex-col justify-center px-5 text-left md:flex-initial md:w-2/3">
              <p className="font-semibold text-gray-800 uppercase">Über mich</p>
              <h1
                className="mb-8 text-2xl font-semibold leading-tight text-gray-800 dark:text-white xl:text-5xl xl:leading-tight"
                style={{
                  fontFamily: '"Frank Ruhl Libre", serif',
                  textTransform: "none",
                }}
              >
                Ich{" "}
                <span
                  style={{
                    fontFamily: '"Frank Ruhl Libre", serif',
                    background:
                      "linear-gradient( 0deg , rgba(255,0,255,0) 0%, rgba(255,0,255,0) 10%, #fde479 10%, #fde479 35%, rgba(255,0,255,0) 35%)",
                  }}
                >
                  lebe jeden Tag
                </span>{" "}
                was ich trainiere.
              </h1>
              <p className="mb-10 text-lg font-medium text-gray-500 md:mb-20">
                Mit unseren weiteren Unternehmen befinden wir uns in der
                täglichen Akquise und bringen Ihnen Erfahrung aus über 9 Jahren
                Neukundengewinnung mit.
                <br />
                <br />
                Deshalb glauben wir zu wissen, was die Herausforderungen jetzt
                und in den nächsten Jahren sein werden. Wir wissen, dass Sie mit
                Motivation und der daraus resultierenden Performance
                Verbesserung zu mehr Erfolg kommen.
                <br />
              </p>
            </div>
          </section>
        </div>
        <div className="flex items-center justify-center -mb-10 bg-white">
          <div className="relative flex flex-col items-center w-full max-w-6xl p-10 mx-auto text-center transform rounded-lg shadow-2xl md:p-16 lg:block bg-gradient-to-br from-yellow-300 via-yellow-300 to-yellow-200 -translate-y-28">
            <h2
              className="my-4 text-3xl font-extrabold tracking-tight text-black sm:text-4xl md:text-5xl lg:my-0 xl:text-4xl sm:leading-tight"
              style={{
                fontFamily: '"Frank Ruhl Libre", serif',
                textTransform: "none",
              }}
            >
              Kostenloses Erstgespräch
            </h2>
            <p className="mt-1 mb-10 text-sm font-medium text-black xl:text-base xl:tracking-wider">
              Vereinbaren Sie jetzt Ihr <i>kostenloses Erstgespräch</i> und
              erhalten Sie ein kostenloses Vertriebstraining zum Thema{" "}
              <strong>Einwandbehandlung: „Einwände lieben lernen“</strong> um
              Ihr Team bei neuen Vorwänden zu unterstützen,{" "}
              <u>sodass Ihr Vertrieb mehr Abschlüsse erzielt</u>.
            </p>
            <div className="flex mb-8 lg:mt-6 lg:mb-0">
              <div className="inline-flex mx-auto">
                <a
                  onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
                  target="_blank"
                  href="https://calendly.com/krauss-friends/kennenlerngespraech"
                  style={{ color: "white !important", background: "#ff0021" }}
                  className="flex items-center self-start px-12 py-4 mr-2 font-medium text-white uppercase transition duration-500 ease-in-out transform border-0 rounded-lg shadow-lg hover:shadow-inner hover:-translate-y-1 hover:scale-110 focus:outline-none text-md"
                >
                  Erstgespräch reservieren
                  <svg
                    className="w-5 h-5 ml-2 fill-current color-white"
                    clasversion="1.1"
                    id="Layer_1"
                    x="0px"
                    y="0px"
                    viewBox="-49 141 512 512"
                  >
                    <path
                      id="XMLID_11_"
                      d="M-24,422h401.645l-72.822,72.822c-9.763,9.763-9.763,25.592,0,35.355c9.763,9.764,25.593,9.762,35.355,0 l115.5-115.5C460.366,409.989,463,403.63,463,397s-2.634-12.989-7.322-17.678l-115.5-115.5c-9.763-9.762-25.593-9.763-35.355,0 c-9.763,9.763-9.763,25.592,0,35.355l72.822,72.822H-24c-13.808,0-25,11.193-25,25S-37.808,422-24,422z"
                    ></path>
                  </svg>
                </a>
              </div>
            </div>
            <p
              onclick="Calendly.initPopupWidget({url: 'https://calendly.com/krauss-friends/kennenlerngespraech?hide_gdpr_banner=1&primary_color=0ba1e2'});return false;"
              className="self-start pt-3 text-sm text-gray-600 cursor-pointer"
            >
              In nur 60 Sekunden online einen freien Termin suchen
            </p>
          </div>
        </div>
        <div className="px-4 pt-16 mx-auto md:px-24">
          <div className="grid gap-10 row-gap-6 mb-8 sm:grid-cols-2 lg:grid-cols-4">
            <div className="sm:col-span-2">
              <a
                href="/"
                aria-label="Zur Startseite"
                title="KRAUSS and Friends"
                className="inline-flex items-center"
              >
                <img
                  src="https://i.ibb.co/1Xn3thH/Krauss-Logo-gen-HKS-47-K-RGB-2000px-72dpi.png"
                  className="w-32"
                />
              </a>
              <div className="mt-6 lg:max-w-sm">
                <p className="text-sm text-gray-800">
                  Wir sind der Trainings- und Consultingspezialist für eine
                  bessere Performance in der Entwicklung von
                  Unternehmenswachstum.
                </p>
                <p className="mt-4 text-sm text-gray-800">
                  Es sind erfolgreiche Menschen, die Unternehmen verändern.
                </p>
              </div>
            </div>
            <div className="space-y-2 text-sm">
              <p className="text-base font-bold tracking-wide text-gray-900">
                Kontakt
              </p>
              <div className="flex">
                <p className="mr-1 text-gray-800">Telefon:</p>
                <a
                  href="#"
                  aria-label="Unser Telefon"
                  title="Unser Telefon"
                  className="transition-colors duration-300 text-purple-accent-400 hover:text-purple-800"
                />
                <a
                  style={{
                    color: "rgba(0,0,238,1.0)",
                    backgroundColor: "rgba(255,255,0,1)",
                    BorderRadius: "3px",
                    cursor: "pointer",
                  }}
                  title="Use as phone number"
                  className="telified"
                  tld="com"
                  nr={+4981919375900}
                  href="tel:+4981919375900"
                  id="idfbf61c55"
                >
                  +49 8191 93759-00
                </a>
              </div>
              <div className="flex">
                <p className="mr-1 text-gray-800">E-Mail:</p>
                <a
                  href="mailto:info@krauss-friends.com"
                  aria-label="Unsere Email"
                  title="Unsere Email"
                  className="transition-colors duration-300 text-purple-accent-400 hover:text-purple-800"
                >
                  info@krauss-friends.com
                </a>
              </div>
              <div className="flex">
                <p className="mr-1 text-gray-800">Adresse:</p>
                <a
                  href="https://www.google.com/maps"
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label="Unsere Adresse"
                  title="Unsere Adresse"
                  className="transition-colors duration-300 text-purple-accent-400 hover:text-purple-800"
                >
                  Ohmstraße 8<br />
                  86899 Landsberg am Lech
                </a>
              </div>
            </div>
            <div>
              <span className="text-base font-bold tracking-wide text-gray-900">
                Social
              </span>
              <div className="flex items-center mt-1 space-x-3">
                <a
                  href="https://www.linkedin.com/company/krauss-and-friends-gmbh"
                  className="text-gray-500 transition-colors duration-300 hover:text-purple-400"
                >
                  <svg fill="currentColor" className="h-5" viewBox="0 0 24 24">
                    <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"></path>
                  </svg>
                </a>
              </div>
              <p className="mt-4 text-sm text-gray-500">
                Sie möchten zu wichtigen Themen rundum Vertrieb, Führung und
                Online Marketing mehr erfahren? Folgen Sie uns auf Social Media
              </p>
            </div>
          </div>
          <div className="flex flex-col-reverse justify-between pt-5 pb-10 border-t lg:flex-row">
            <p className="text-sm text-gray-600">
              © Copyright 2011-2021 KRAUSS AND FRIENDS. All rights reserved.
            </p>
            <ul className="flex flex-col mb-3 space-y-2 lg:mb-0 sm:space-y-0 sm:space-x-5 sm:flex-row">
              <li>
                <a
                  href="/about"
                  className="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400"
                >
                  Impressum
                </a>
              </li>
              <li>
                <a
                  href="/j/privacy"
                  className="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400"
                >
                  Datenschutzerklärung
                </a>
              </li>
              <li>
                <a
                  id="cookie-policy"
                  href="javascript:window.CookieControl.showCookieSettings();"
                  className="text-sm text-gray-600 transition-colors duration-300 hover:text-deep-purple-accent-400"
                  name="cookie-policy"
                >
                  Cookie-Richtlinie
                </a>
              </li>
            </ul>
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
